### ISSUE TITLE
Ice Palace + Flippers

### ISSUE THREAD

**Issue by lemabr01** [wolfman2000/stumpy#81]
Ice Palace appears to always require the Flippers + Moon Pearl although it can be accessed with minor glitches without those items.  It shows up red until you have Flippers + Moon Pearl + Titan's Mitt, although you can reach it with fake flippers (avoiding Flippers) and then you can die inside (avoiding Moon Pearl). 

Based on this and my read of your sequence break/glitch requirements, I believe Ice Palace should have a white border around it once you mark Titan's Mitt.

See attached image.

![image](https://user-images.githubusercontent.com/25397001/40817621-6ef849f2-6521-11e8-9f52-a9e12102e2e1.png)

**Comment by wolfman2000** [comment]
Sorry for the delay. I am aware of both fake flippers and fairy revival minor glitches. However, I'm not sure I want to go that route since some runners may want to use this tracker for OHKO mode for some reason.

If I were to add a separate setting for this, then maybe it would be worth considering.
